// The single source of truth for turning a free-text location string into structured
// city/state — used by both the admin backfill panel and, later, any form that wants
// it. Deliberately conservative: only returns confident:true when the string is
// unambiguously "City, ST" or "City, State Name" shaped. A bare "Chicago" or an
// ambiguous "Logan Square, Chicago" (same shape as "Chicago, Illinois" — only the
// state-name lookup tells them apart) comes back not-confident and is left for a
// human to fill in via the profile form — never guessed, never silently written.

import { slugify } from '@/lib/slugify'

// Census place/county names include non-ASCII characters (Puerto Rico: "Boquerón",
// "Añasco") that plain slugify() would mangle into garbage ("boquer-n") since its
// regex only keeps a-z0-9. NFD-normalizing and stripping combining marks first fixes
// that — and is a complete no-op for any ASCII input, so geoSlug('Chicago') is
// byte-identical to slugify('Chicago'). Existing entity slugs (built with plain
// slugify()) are never touched or regenerated by this.
const COMBINING_DIACRITICS = /[̀-ͯ]/g

export function geoSlug(text) {
  const stripped = text.normalize('NFD').replace(COMBINING_DIACRITICS, '')
  return slugify(stripped)
}

// Census's LSAD (Legal/Statistical Area Description) code, from the Gazetteer place
// file — distinguishes an incorporated city from a town/village/CDP/etc. Codes below
// are every value actually present in the 2024 national places file.
export const LSAD_LABELS = {
  '25': 'city',
  '43': 'town',
  '47': 'village',
  '21': 'borough',
  '57': 'CDP', // Census Designated Place — an unincorporated community, no local government
  '55': 'comunidad', // Puerto Rico
  '62': 'zona urbana', // Puerto Rico
  '35': 'metro township',
  '37': 'municipality',
  '53': 'city and borough',
  '00': 'balance',
  CG: 'consolidated government',
  CN: 'consolidated government',
  MG: 'metropolitan government',
  UC: 'unified government',
  UG: 'unified government',
}

export function lsadLabel(code) {
  return LSAD_LABELS[code] || 'place'
}

export const usStateAbbreviations = {
  alabama: 'AL', alaska: 'AK', arizona: 'AZ', arkansas: 'AR', california: 'CA',
  colorado: 'CO', connecticut: 'CT', delaware: 'DE', florida: 'FL', georgia: 'GA',
  hawaii: 'HI', idaho: 'ID', illinois: 'IL', indiana: 'IN', iowa: 'IA',
  kansas: 'KS', kentucky: 'KY', louisiana: 'LA', maine: 'ME', maryland: 'MD',
  massachusetts: 'MA', michigan: 'MI', minnesota: 'MN', mississippi: 'MS', missouri: 'MO',
  montana: 'MT', nebraska: 'NE', nevada: 'NV', 'new hampshire': 'NH', 'new jersey': 'NJ',
  'new mexico': 'NM', 'new york': 'NY', 'north carolina': 'NC', 'north dakota': 'ND', ohio: 'OH',
  oklahoma: 'OK', oregon: 'OR', pennsylvania: 'PA', 'rhode island': 'RI', 'south carolina': 'SC',
  'south dakota': 'SD', tennessee: 'TN', texas: 'TX', utah: 'UT', vermont: 'VT',
  virginia: 'VA', washington: 'WA', 'west virginia': 'WV', wisconsin: 'WI', wyoming: 'WY',
  'district of columbia': 'DC', 'puerto rico': 'PR',
}

const VALID_STATE_CODES = new Set(Object.values(usStateAbbreviations))
const STATE_NAME_BY_CODE = Object.fromEntries(Object.entries(usStateAbbreviations).map(([name, code]) => [code, name]))

// [code, "Title Case Name"] pairs, alphabetized by name — the one list every state
// <select> in the app renders from, so they can never drift apart.
export const US_STATE_OPTIONS = Object.entries(usStateAbbreviations)
  .map(([name, code]) => [code, name.replace(/\b\w/g, c => c.toUpperCase())])
  .sort((a, b) => a[1].localeCompare(b[1]))

// 'IL' -> 'Illinois', for display where a page wants the full name.
export function stateLabel(code) {
  const name = STATE_NAME_BY_CODE[code?.toUpperCase()]
  return name ? name.replace(/\b\w/g, c => c.toUpperCase()) : code
}

export function parseLocationString(raw) {
  if (!raw || typeof raw !== 'string') return { city: null, state: null, confident: false }
  const parts = raw.split(',').map(s => s.trim()).filter(Boolean)
  if (parts.length !== 2 || !parts[0] || !parts[1]) return { city: null, state: null, confident: false }

  const [city, statePart] = parts
  const upper = statePart.toUpperCase()
  if (VALID_STATE_CODES.has(upper)) return { city, state: upper, confident: true }

  const lower = statePart.toLowerCase()
  if (usStateAbbreviations[lower]) return { city, state: usStateAbbreviations[lower], confident: true }

  return { city: null, state: null, confident: false }
}
